pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }   
        }
        stage('CPU details') {
            steps {
                echo 'here is brief CPU details'
                sh '''
                    lscpu
                '''
            }
        }
    }
}
